name: down-bot

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 */3 * * *"

permissions:
  contents: write

jobs:
  run-down-bot:
    runs-on: ubuntu-latest

    env:
      FB_TOKEN: ${{ secrets.FB_TOKEN }}
      IMG_TOKEN: ${{ secrets.IMG_TOKEN }}
      GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}

    steps:
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.13
          architecture: x64 

      - name: Upgrade pip to latest stable
        run: |
          python -m pip install --upgrade pip

      - name: Instalar Dependências
        run: |
          python -m pip install -r requirements.txt

      - name: Executar script Python
        run: python main.py

      - name: Update arquivos
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "updated"
          file_pattern: replyed_ids.txt
          push_options: '--force'
          
      
      - name: Acionar o workflow
        run: |
            WORKFLOW_NAME="down-bot.yml"
            REPO="${{ github.repository }}"
            BRANCH_NAME="${{ github.ref_name }}"
  
            retries=0
            max_retries=3
  
            while [[ $retries -lt $max_retries ]]; do
              response=$(curl -o /dev/null -s -w "%{http_code}" -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                -d "{\"ref\":\"$BRANCH_NAME\"}" \
                "https://api.github.com/repos/$REPO/actions/workflows/$WORKFLOW_NAME/dispatches")
  
              if [[ $response -ge 200 && $response -lt 300 ]]; then
                echo "Workflow acionado com sucesso!"
                exit 0
              else
                echo "Erro ao acionar workflow (tentativa $((retries + 1))/$max_retries): HTTP $response"
                retries=$((retries + 1))
                sleep 5
              fi
            done
  
            if [[ $retries -eq $max_retries ]]; then
              echo "Falha após $max_retries tentativas."
              exit 1
            fi
  



          
